controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    boom_controller:
      type: joint_trajectory_controller/JointTrajectoryController

boom_controller:
  ros__parameters:
    joints:
      - boom_turret_joint
      - boom_elevation_joint
      - boom_extension_1_joint
      - boom_extension_2_joint
      - boom_extension_3_joint
      - boom_extension_4_joint
      - platform_level_joint
      - rail_carriage_joint
      - cutting_arm_lift_joint
      - cutting_arm_extension_joint
    command_interfaces: [position]
    state_interfaces: [position, velocity]
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
